export const TOTAL_NUMBER_INCREASE = 'TOTAL_NUMBER_INCREASE';
export const TOTAL_NUMBER_DECREASE = 'TOTAL_NUMBER_DECREASE';
export const TOTAL_NUMBER_RESET = 'TOTAL_NUMBER_RESET';

export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
